SQLite için datasource tanımı eklemeleri
suckerman7/JavaRestAPI-Demo pull request #7
Opened 2024-03-21 08:53 UTC by Suckerman7

İlk issue'da yapılması gereken her şeyi yaptım. Kontrol ederseniz memnun olurum.

2024-03-26 19:38 UTC, Suckerman7 commented
Bu task'ta daha yapmam gereken ne vardı? Geçen haftaki toplantıdan sonra buraya yorum eklenmeyince ve ayrıca geçen günlerde de sınavlarıma çalıştığım için maalesef unuttum. Bana hatırlatabilirseniz memnun olurm.

2024-03-28 10:34 UTC, Suckerman7 commented
toplantıda dediğiniz eklemeleri hem application.properties hem de persistence.properties dosyalarına ekledim. Son commit'ime göz atarsanız memnun olurum.

Ama bu pull request'in içinde de şu an Maven Action hatası ortaya çıktı. Sanıyorsam bu PR'i main ile mergeledikten sonra hata gidebilir.

2024-04-04 10:21 UTC, hyperpostulate requested changes

2024-04-04 10:21 UTC, hyperpostulate commented on src/main/java/org/mertyuksel/restapidemo/RestApiDemoApplication.java
Datasource'a dair bean tanımını config paketi içerisinde yer alacak DataAccessConfiguration sınıfına alalım.

2024-04-04 10:21 UTC, hyperpostulate commented on src/main/resources/persistence-sqlite.properties
url tanımında inmemory değil, file based tanım yapalım. dosya yolunu belirtirken de relative path kullanalım.

2024-04-04 10:51 UTC, Suckerman7 commented on src/main/java/org/mertyuksel/restapidemo/RestApiDemoApplication.java
Config paketi içinde şimdi sınıf ile aynı adı taşıyan bir .java dosyasına ekledim Bean tanımını.

2024-04-04 10:51 UTC, Suckerman7 commented on src/main/resources/persistence-sqlite.properties
Bunu da son commit'imde hallettim. Göz atabilirseniz memnun olurum.

2024-04-18 10:11 UTC, hyperpostulate commented on src/main/java/org/mertyuksel/restapidemo/RestApiDemoApplication.java
import'lar yok :)

2024-04-18 11:41 UTC, Suckerman7 commented on src/main/java/org/mertyuksel/restapidemo/RestApiDemoApplication.java
4 hatayı gerekli importları ekleyerek tek bir hataya indirgedim. Ama hala DataSource Class'ı için "cannot find symbol" hatası veriyor. Araştırsam da hiç işe yaracak bir çözüm maalesef bulamadım.

Yaptıklarımı pushlayıp siz de bir göz atabilirseniz memnun olurum.

2024-04-25 10:07 UTC, merged

2024-05-16 08:44 UTC, suckerman7 commented on src/main/java/org/mertyuksel/restapidemo/RestApiDemoApplication.java
Mesut bey, uygulamayı sonunda local'de ayağa kaldırabildim. Şimdi Furkan bey ile birlikte hallettik.